global using ComputerLock.Resources;
global using ComputerLock.Enums;
global using ComputerLock.Hooks;
global using ComputerLock.Platforms;
global using JiuLing.CommonLibs.ExtensionMethods;
global using MudBlazor;
global using ComputerLock.Components;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.Localization;